AllCops:
  Exclude:
    - './bin/*'
    - './spec/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'test/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
